<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="true" time="0" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2021-06-05T12:57:31" tests="1" file="cypress/integration/examples/calculatesItemPrice.js" failures="1" time="0">
    <testcase name="An uncaught error was detected outside of a test" time="0" classname="An uncaught error was detected outside of a test" failure="true" error="true" success="false">
      <failure message="The following error originated from your test code, not from Cypress.

  &gt; g is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure." type="ReferenceError"><![CDATA[ReferenceError: The following error originated from your test code, not from Cypress.

  > g is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at Suite.eval (http://localhost:27327/__cypress/tests?p=cypress\integration\examples\calculatesItemPrice.js:104:3)
    at Object../cypress/integration/examples/calculatesItemPrice.js (http://localhost:27327/__cypress/tests?p=cypress\integration\examples\calculatesItemPrice.js:99:1)
    at __webpack_require__ (http://localhost:27327/__cypress/tests?p=cypress\integration\examples\calculatesItemPrice.js:20:30)
    at Object.0 (http://localhost:27327/__cypress/tests?p=cypress\integration\examples\calculatesItemPrice.js:152:18)
    at __webpack_require__ (http://localhost:27327/__cypress/tests?p=cypress\integration\examples\calculatesItemPrice.js:20:30)
    at eval (http://localhost:27327/__cypress/tests?p=cypress\integration\examples\calculatesItemPrice.js:84:18)
    at eval (http://localhost:27327/__cypress/tests?p=cypress\integration\examples\calculatesItemPrice.js:87:10)
    at eval (<anonymous>)]]></failure>
    </testcase>
  </testsuite>
</testsuites>